[package]
edition = '2018'
name = "jexl-parser"
version = "0.1.0"
authors = ["Mike Cooper <mythmon@gmail.com>"]
build = "build.rs"

[dependencies]
lalrpop-util = "0.19"
regex = "1.3"

[build-dependencies]
lalrpop = {version = "0.19", features = ["lexer"]}
